VOWELS = ["a", "ı", "o", "u", "e", "i", "ö", "ü"]
HARD_VOWELS = ["a", "ı", "o", "u"]
SOFT_VOWELS = ["e", "i", "ö", "ü"]
HARD_CONS = ["k", "t", "ç", "p"]
PARTS_OF_SPEECH = ["noun", "pronoun", "adjective", "verb", "adverb", "postposition", "conjunction", "particle", "interjection"]
API_URL = "https://en.wiktionary.org/w/api.php?"

REQ_HEADERS = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate',
        'DNT': '1',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1'
    }
    
DERIVE_SUFFIXES = [
    "-lik", "-lık", "-luk", "-lük",
    "-li", "-lı", "-lu", "-lü",
    "-siz", "-sız", "-suz", "-süz",
    "-cı", "-ci", "-cu", "-cü",
    "-çı", "-çi", "-çu", "-çü",
    "-cık", "-cik", "-cuk", "-cük",
    "-çık", "-çik", "-çuk", "-çük",
    "-ca", "-çe",
    "-ça", "-çe",
    "-daş", "-deş", "-taş", "-teş",
    "-ncı", "-nci", "-ncu", "-ncü",
    "-ar", "-er", "-şar", "-şer",
    "-sal", "-sel",
    "-tı", "-ti", "-tu", "-tü",
    "-aç", "-eç", 
    "-ak", "-ek", 
    "-an", "-en", 
    "-cıl", "-cil", "-cul", "-cül", "-çıl", "-çil", "-çul", 
    "-cileyin", 
    "-ç", 
    "-gil", "-gül", "-kıl", "-kil", 
    "ge -ka", 
    "-kan", "-ken", 
    "-man", "-men", 
    "-la", 
    "-lak", "-lek", 
    "-layın", "-leyin", 
    "-msı", "-msi", "-msu", 
    "-mtırak", 
    "-rak", "-rek", 
    "-sak", "-sek", 
    "-sı", "-si", "-su", "-sü", 
    "-şın", "-şin", 
    "-t", 
    "-z", 
    "-la", "-le", 
    "-n", "-ş", "-t", 
    "-laş", "-leş",
    "-al", "-el", 
    "-l", 
    "-a", "-e", 
    "-ar", "-er", 
    "-da", "-de", 
    "-k", 
    "-kır", "-kir", "-kur", "-kür", 
    "-msa", "-mse", 
    "-r", 
    "-sa", "-se", 
    "-l",  
    "-ma", "-me", 
    "-n",  
    "-r", 
    "-ç", "-ğ", "-p", "-ş", "-t", "-y", 
    "-t", 
    "-ş", 
    "-dır", "-dir", "-dur", "-dür", "-tır", "-tir", "-tur", "-tür", 
    "-a", "-e", 
    "-ala", "-ele", 
    "-ar", "-er", 
    "-ı", "-ü", 
    "-k", 
    "-p",  
    "-gan", "-gen", "-kan", "-ken", 
    "-gı", "-gi", "-gu", "-gü", "-kı", "-ki", "-ku", "-kü", 
    "-gın", "-gin", "-gun", "-gün", "-kın", "-kin", "-kun", "-kün", 
    "-ı", "-i", "-u", "-ü", 
    "-ıcı", "-ici", "-ucu", "-ücü", 
    "-ış", "-iş", "-uş", "-üş", 
    "-k", 
    "-m", 
    "-ma", "-me", 
    "-mak", "-mek", 
    "-tı", "-ti", "-tu", "-tü", 
    "-a", "-e", 
    "-ağan", "-eğen", 
    "-ak", "-ek", 
    "-alak", "-elek ", 
    "-amak", "-emek ", 
    "-anak", "-enek", 
    "-ca", "-ce", 
    "-ç", 
    "-n", 
    "-aç", "-eç", 
    "-dı", "-di", "-du", "-dü", "-tı", "-ti", "-tu", "-tü", 
    "-ga", "-ge", 
    "-gaç", "-geç", "-kaç", 
    "-gıç", "-giç", "-guç", 
    "-maca", "-mece", 
    "-maç", "-meç", 
    "-man", "-men", 
    "-mık", "-mik", "-muk", 
    "-n", 
    "-t", 
    "-am", 
    "-al", 
    "-arı", 
    "-eri", 
    "-baç", 
    "-baç", 
    "-ceme", 
    "-l", 
    "-mur", 
    "-pak", 
    "-sak", 
    "-van", 
    "-acak", "-ecek", 
    "-an", "-en", 
    "-ar", "-er", 
    "-ası", "-esi", 
    "-dık", "-dik", "-duk", "-dük", "-tık", "-tik", "-tuk", "-tük", 
    "-diğ", 
    "-diğ", 
    "-duğ", 
    "-düğ", 
    "-tığ", 
    "-tiğ", 
    "-tüğ", 
    "-maz", "-mez", 
    "-mış", "-miş", "-muş", "-müş", 
    "-r", 
    "-a", "-e", 
    "-alı", "-eli", 
    "-alı", 
    "-arak", "-erek", 
    "-dan", "-den", 
    "-tan", "-ten", 
    "-dıkça", "-dikçe", "-dukça", "-dükçe", "-tıkça", "-tikçe", "-tukça", "-tükçe", 
    "-ı", "-i", "-u", "-ü", 
    "-ınca", "-ince", "-unca", "-ünce", 
    "-ıp", "-ip", "-up", "-üp", 
    "-ken", 
    "-madan", "-meden",
    "-im", "-ım"
    ]


mi_particles = ["mi", "mı", "mu", "mü"]

SUFFIXES = ['-lik', '-lık', '-luk', '-lük', '-li', '-lı', '-lu', '-lü', '-siz', '-sız', '-suz', '-süz', '-cı', '-ci', '-cu', '-cü', '-çı', '-çi', '-çu', '-çü', '-cık', '-cik', '-cuk', '-cük', '-çık', '-çik', '-çuk', '-çük', '-ca', '-çe', '-ça', '-daş', '-deş', '-taş', '-teş', '-ncı', '-nci', '-ncu', '-ncü', '-ar', '-er', '-şar', '-şer', '-sal', '-sel', '-tı', '-ti', '-tu', '-tü', '-aç', '-eç', '-ak', '-ek', '-an', '-en', '-cıl', '-cil', '-cul', '-cül', '-çıl', '-çil', '-çul', '-cileyin', '-ç', '-gil', '-gül', '-kıl', '-kil', 'ge -ka', '-kan', '-ken', '-man', '-men', '-la', '-lak', '-lek', '-layın', '-leyin', '-msı', '-msi', '-msu', '-mtırak', '-rak', '-rek', '-sak', '-sek', '-sı', '-si', '-su', '-sü', '-şın', '-şin', '-t', '-z', '-le', '-n', '-ş', '-laş', '-leş', '-al', '-el', '-l', '-a', '-e', '-da', '-de', '-k', '-kır', '-kir', '-kur', '-kür', '-msa', '-mse', '-r', '-sa', '-se', '-ma', '-me', '-ğ', '-p', '-y', '-dır', '-dir', '-dur', '-dür', '-tır', '-tir', '-tur', '-tür', '-ala', '-ele', '-ı', '-ü', '-gan', '-gen', '-gı', '-gi', '-gu', '-gü', '-kı', '-ki', '-ku', '-kü', '-gın', '-gin', '-gun', '-gün', '-kın', '-kin', '-kun', '-kün', '-i', '-u', '-ıcı', '-ici', '-ucu', '-ücü', '-ış', '-iş', '-uş', '-üş', '-m', '-mak', '-mek', '-ağan', '-eğen', '-alak', '-elek ', '-amak', '-emek ', '-anak', '-enek', '-ce', '-dı', '-di', '-du', '-dü', '-ga', '-ge', '-gaç', '-geç', '-kaç', '-gıç', '-giç', '-guç', '-maca', '-mece', '-maç', '-meç', '-mık', '-mik', '-muk', '-am', '-arı', '-eri', '-baç', '-ceme', '-mur', '-pak', '-van', '-acak', '-ecek', '-ası', '-esi', '-dık', '-dik', '-duk', '-dük', '-tık', '-tik', '-tuk', '-tük', '-diğ', '-duğ', '-düğ', '-tığ', '-tiğ', '-tüğ', '-maz', '-mez', '-mış', '-miş', '-muş', '-müş', '-alı', '-eli', '-arak', '-erek', '-dan', '-den', '-tan', '-ten', '-dıkça', '-dikçe', '-dukça', '-dükçe', '-tıkça', '-tikçe', '-tukça', '-tükçe', '-ınca', '-ince', '-unca', '-ünce', '-ıp', '-ip', '-up', '-üp', '-madan', '-meden', '-im', '-ım', '-ler', '-lar', '-üm', '-um', '-yim', '-yım', '-yüm', '-yum', '-sin', '-sın', '-sün', '-sun', '-iz', '-ız', '-üz', '-uz', '-yiz', '-yız', '-yüz', '-yuz', '-siniz', '-sınız', '-sünüz', '-sunuz', '-tirler', '-tırlar', '-türler', '-turlar', '-dirler', '-dırlar', '-dürler', '-durlar', '-lerdir', '-lardır', '-ydi', '-ydı', '-ydü', '-ydu', '-ymiş', '-ymış', '-ymüş', '-ymuş', '-yse', '-ysa', '-yi', '-yı', '-yü', '-yu', '-ye', '-ya', '-te', '-ta', '-in', '-ın', '-ün', '-un', '-nin', '-nın', '-nün', '-nun', '-yle', '-yla', '-lerim', '-larım', '-imiz', '-ımız', '-ümüz', '-umuz', '-miz', '-mız', '-müz', '-muz', '-lerimiz', '-larımız', '-lerin', '-ların', '-iniz', '-ınız', '-ünüz', '-unuz', '-niz', '-nız', '-nüz', '-nuz', '-leriniz', '-larınız', '-leri', '-ları', '-ebil', '-abil', '-yebil', '-yabil', '-eme', '-ama', '-yeme', '-yama', '-yip', '-yıp', '-yüp', '-yup', '-yerek', '-yarak', '-yince', '-yınca', '-yünce', '-yunca', '-mem', '-mam', '-mezsin', '-mazsın', '-meyiz', '-mayız', '-mezsiniz', '-mazsınız', '-mezler', '-mazlar', '-eyım', '-ayım', '-yeyim', '-yayım', '-esin', '-asın', '-elim', '-alım', '-yelim', '-yalım', '-esiniz', '-asınız', '-yesiniz', '-yasınız', '-eler', '-alar', '-yeler', '-yalar', '-yin', '-yın', '-yün', '-yun', '-yiniz', '-yınız', '-yünüz', '-yunuz', '-sinlar', '-sınlar', '-sünlar', '-sunlar', '-ir', '-ır', '-ür', '-ur', '-emez', '-amaz', '-yemez', '-yamaz', '-iyor', '-ıyor', '-üyor', '-uyor', '-yecek', '-yacak', '-mekte', '-makta', '-meli', '-malı']

TURKIC_LANGS = ['Oghuz languages', 'Karluk languages', 'Kipchak languages', 'Siberian Turkic languages',
'Arghu Turkic language', 'Oghur languages', 'Turkic languages', 'Turkish language', 'Uzbek language',
'Azerbaijani language', 'Uyghur language', 'Kazakh language', 'Turkmen language', 'Tatar language',
'Kyrgyz language', 'Bashkir language', 'Chuvash language', 'Qashqai language', 'Khorasani Turkic language',
'Karakalpak language', 'Crimean Tatar language', 'Kumyk language', 'Karachay-Balkar language',
'Yakut language', 'Tuvan language', 'Urum language', 'Gagauz language', 'Siberian Tatar language',
'Nogai language', 'Salar language', 'Altai language', 'Khakas language', 'Khalaj language',
'Äynu language', 'Western Yugur language', 'Shor language', 'Dolgan language', 'Krymchak language',
'Ili Turki language', 'Tofa language', 'Karaim language', 'Chulym language', 'Common Turkic languages',
'Proto Turkic', 'Old Turkic', 'Old Anatolian Turkish', 'Pecheneg', 'Orkhon Turkic', 'Khazar', 'Old Uyghur',
'Khorezmian', 'Bulgar', 'Middle Turkic', 'Kipchak', 'Cuman', 'Old Tatar', 'Fergana Kipchak', 'Chagatai',
'Ottoman Turkish', 'Fuyu Girgis', 'Dukhan', 'Salchuq', 'Rumelian dialect', 'Cypriot dialect',
'Afshar dialect', 'Sonqori dialect', 'Lop dialect', 'Baraba dialect', 'Turkic', 'Proto-Turkic', "Karakhanid"]